name: flutter_generator
description: Advanced dart/flutter dev tool for generating page, widget, model, repository, and bloc etc.
version: 1.0.5
homepage: https://github.com/pravinkumarputta/flutter_generator

executables:
  flutter_generator:

environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
dependencies: 
  args: ^2.3.0
